# Generated by Django 4.2.4 on 2023-09-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='category', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cook_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('category', models.CharField(default='anycategory', max_length=100)),
                ('text', models.TextField(default='reciept')),
            ],
        ),
    ]
