# Generated by Django 4.2.4 on 2023-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
