# Generated by Django 4.1.1 on 2022-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='advert',
            name='CategoryType',
            field=models.CharField(choices=[('танк', 'танк'), ('хиллы', 'хиллы'), ('ДД', 'ДД'), ('торговец', 'торговец'), ('гилдмастер', 'гилдмастер'), ('Квестгивер', 'Квестгивер'), ('Кузнец', 'Кузнец'), ('Кожевник', 'Кожевник'), ('Зельевар', 'Зельевар'), ('Мастер заклинаний', 'Мастер заклинаний')], max_length=17),
        ),
    ]
